FROM node:16.14.2-alpine as builder
WORKDIR /usr/app/webserver
RUN apk add ffmpeg
RUN npm install -g nodemon ts-node
COPY package.json .
RUN npm install --quiet

FROM builder
COPY . .
RUN chmod +x /usr/app/webserver/run.sh

EXPOSE 3000
CMD "/usr/app/webserver/run.sh"